/**
 * ============================================================
 * Stockdity IMS — Configuration File
 * ============================================================
 *
 * PURPOSE:
 *   This is the ONLY file that changes between customer deployments.
 *   The seller customises these values for each buyer before delivery.
 *
 * LICENCE KEY SETUP (for sellers):
 *   – Use the included keygen.html to generate a public/private key pair.
 *   – Paste the PUBLIC key (JWK) into LICENCE_PUBLIC_KEY below.
 *   – Keep the PRIVATE key secret and use it to sign licence keys.
 *   – NEVER put the private key or any raw licence key here.
 *
 * SECURITY NOTE:
 *   The licence key is a signed JSON token. The signature can only be
 *   created with the seller’s private key, which is never shared.
 *   This makes keys unforgeable without a server.
 *
 * ============================================================
 */

const AppConfig = Object.freeze({

  // ── LICENCE ──────────────────────────────────────────────────────────────
  /**
   * ECDSA public key (JWK) used to verify signed licence tokens.
   * Generated by the seller with keygen.html — keep the private key safe!
   */
  LICENCE_PUBLIC_KEY: {
    kty: "EC",
    crv: "P-256",
    x: "yne5pi7LnrsBkDt2ZUiPerwaLmLVrV8lMWlLlHEHzmE",
    y: "UQ-5t8GDVtG6V0RevAKhvbDssgqbepGyaokiudAoKsQ"
  },

  // ── APPLICATION IDENTITY ─────────────────────────────────────────────────
  APP_NAME:               'Stockdity IMS',
  APP_TAGLINE:            'Inventory. Simplified.',
  APP_VERSION:            '1.0.0',
  APP_RELEASE_DATE:       '2025-01-01',

  // ── LOCALISATION ─────────────────────────────────────────────────────────
  DEFAULT_CURRENCY_SYMBOL: '₦',
  DEFAULT_TIMEZONE:        'Africa/Lagos',
  DEFAULT_DATE_FORMAT:     'DD/MM/YYYY',

  // ── DEFAULTS ─────────────────────────────────────────────────────────────
  DEFAULT_LOW_STOCK_THRESHOLD: 10,
  DEFAULT_PAGE_SIZE:           20,
  MAX_IMAGE_SIZE_BYTES:        2097152,
  MAX_LOGO_SIZE_BYTES:         1048576,
  ALLOWED_IMAGE_TYPES:         ['image/jpeg', 'image/png', 'image/webp'],

  // ── SECURITY ─────────────────────────────────────────────────────────────
  MAX_LOGIN_ATTEMPTS:        5,
  LOGIN_ATTEMPT_WINDOW_MS:   600000,
  LOCKOUT_DURATION_MS:       900000,

  // ── NOTIFICATIONS ────────────────────────────────────────────────────────
  EXPIRY_WARNING_DAYS:   30,
  TOPBAR_NOTIF_LIMIT:    5,

  // ── PERFORMANCE ──────────────────────────────────────────────────────────
  SEARCH_DEBOUNCE_MS:        300,
  SCROLL_TOP_THRESHOLD_PX:   300,

  // ── DATABASE ─────────────────────────────────────────────────────────────
  DB_NAME:    'StockdityIMS',
  DB_VERSION: 1,

  // ── SEED ─────────────────────────────────────────────────────────────────
  SEED_ADMIN_EMAIL:    'admin@app.com',
  SEED_ADMIN_PASSWORD: 'Admin@1234',
  SEED_ADMIN_NAME:     'System Administrator',

  // ── STORAGE KEYS ─────────────────────────────────────────────────────────
  STORAGE_KEYS: Object.freeze({
    ACTIVATION:     'stockdity_activation',
    LOGIN_ATTEMPTS: 'stockdity_login_attempts',
    SIDEBAR_STATE:  'stockdity_sidebar_collapsed'
  }),

  SESSION_KEYS: Object.freeze({
    AUTH_USER:   'auth_user',
    SALES_CART:  'sales_cart'
  }),

  // ── ROLE HIERARCHY ───────────────────────────────────────────────────────
  ROLE_HIERARCHY: ['staff', 'manager', 'admin'],

  // ── UI THEME ─────────────────────────────────────────────────────────────
  DEFAULT_PRIMARY_COLOR: '#4F46E5',

  // ── REPORT DEFAULTS ──────────────────────────────────────────────────────
  TOP_PRODUCTS_LIMIT:   20,
  DASHBOARD_TREND_DAYS: 30
});

window.AppConfig = AppConfig;
export default AppConfig;
